import Header from "@/shared/components/header";
import type { Metadata } from "next";
import { NextIntlClientProvider, useMessages } from "next-intl";
import { Lexend_Deca, Tajawal } from "next/font/google";
import { ReactNode } from "react";
import "../global.scss";
import { LayoutCustom } from "@/shared/components/LayoutCustom";
import 'mapbox-gl/dist/mapbox-gl.css';

const lexend_Deca = Lexend_Deca({
  subsets: ["latin"],
  variable: "--font-inter-deca",
  weight: [ "200", "300", "400", "500", "600", "700", "800", "900"],
});

const tajawal = Tajawal({
  subsets: ["arabic"],
  variable: "--font-inter",
  weight: [ "200", "300", "400", "500",  "700", "800", "900"],

});

export const metadata: Metadata = {
  title: "e-Procure",
  description: "Generated by e-Procure",
};

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: ReactNode;
  params: {
    locale: string;
  };
}) {
  const messages = useMessages();

  return (
    <html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"}>
      <head>
      <link rel="manifest" href="./manifest.json" />
      </head>
      <body
        className={locale === "ar" ? tajawal.className : lexend_Deca.className}
      >
        <NextIntlClientProvider messages={messages}>
          <LayoutCustom locale={locale}>{children}</LayoutCustom>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
